runs:
  using: "composite"
  steps:
    - name: Install 3rd party from apt
      run: sudo apt install unar zlib1g-dev liblzo2-dev lzop lziprecover
      shell: bash

    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip

    - name: Pip install
      run: python -m pip install --upgrade pip poetry
      shell: bash

    - name: Restore poetry cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pypoetry/cache
          ~/.cache/pypoetry/artifacts
        key: poetry-cache-and-artifacts

    - name: Restore virtualenvs
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Poetry install
      run: poetry install
      shell: bash
