name: "Nix"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup git lfs
      uses: ./.github/actions/setup-git-lfs

    - uses: cachix/install-nix-action@v19
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: unblob
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix flake check -L
    - run: |
        nix build -L ".#unblob.withTests" "github:onekey-sec/unblob/$GITHUB_SHA"
