name: Rust Binding

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.lock'
      - 'rust/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'Cargo.lock'
      - 'rust/**'


jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: 1.57.0

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build cargo bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --no-run
