name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install 3rd party from apt
        run: |
            sudo apt install unar zlib1g-dev liblzo2-dev lzop

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install

      - name: Create LFS file hash list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
            path: .git/lfs
            key: lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: git lfs pull

      - name: Run pytest
        # TODO: Dummy coverage (branch: 0%) is needed for the pass rate. Increase this
        run: poetry run pytest --cov=. --cov-branch --cov-fail-under=0
